[project]
name = "agentops-openai-docs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agentops>=0.3.21",
    "openai>=1.57.4",
    "packaging>=24.2",
    "python-dotenv>=1.0.1",
]
