[tool.poetry]
name = "agentops-openai-docs"
version = "0.1.0"
description = ""
authors = ["tad dy <a@a.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
openai = "^1.57.4"
python-dotenv = "^1.0.1"
agentops = "^0.3.21"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
